spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: sta_apollo
            client-secret: 981a2860-2a07-4318-b57e-d01f2b3b2081
            authorization-grant-type: client_credentials
            scope:
            - bid
        provider:
          sso:
            issuer-uri: https://login.sso.az.run.withtanzu.com
